redis:
    image: redis
    container_name: redis
    ports:
    - 6379:6379
    expose:
    - 6379

hub-processor:
    links:
    - redis
    environment:
    - SERVER_PORT=9000
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    build: ./hub-processor
    ports:
    - 9000:9000
    expose:
    - 9000

hub-api:
    links:
    - redis
    environment:
    - SERVER_PORT=8080
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    build: ./hub-api
    ports:
    - 8080:8080
    expose:
    - 8080